### ISSUE TITLE
Transfer repository to univention?

### ISSUE THREAD

**Issue by spaceone** [univention/python-notifier#18]
Hi crunchy,

can you transfer the ownership of this repository to univention/ or make me an admin, so I can transfer it?

Best regards

**Comment by crunchy-github** [comment]
Hi,

I would like to transfer it, but as you and Univention already have a repository with the same name the transfer is not possible. As soon as you have removed the repository I can try the transfer again.

kind regards
crunchy

**Comment by spaceone** [comment]
@crunchy-github I renamed the Univention repository. Please try again :-)

**Comment by crunchy-github** [comment]
New error message :-D

univention already has a repository in the crunchy-github/python-notifier network and You don’t have the permission to create public repositories on univention

**Comment by spaceone** [comment]
@crunchy-github Ok, I pushed all our changes to the repository and removed our repository. And I invited you to the univention organistion with temporary permissions to create repositories there.

**Comment by crunchy-github** [comment]
Almost ... ;-)

You don’t have the permission to create public repositories on univention

**Comment by spaceone** [comment]
@crunchy-github You did not yet accept the invitation to the Univention organization. You should have received an email with a confirm invitation link. Then it should work.

**Comment by crunchy-github** [comment]
Done :-) Thanks for taking over the project! Greetings to all my old co-workers :-)

**Comment by spaceone** [comment]
Thanks for the project itself, it introduced me to the asynchronous programming style ;-)
