### ISSUE TITLE
provide debian packages

### ISSUE THREAD

**Issue by spaceone** [univention/python-notifier#6]
hi,

will you provide a debian package for the new 0.9.6 release?

**Comment by pmhahn** [comment]
The debian/control file contains non-UTF-8 characters.
Please convert all debian/* files to UTF-8.
See commit 5aa876f5aff76ae6aeb5db6a8f0f3af6058ac417 for the change of all other files to UTF-8.

**Comment by spaceone** [comment]
The package now contains a debian directory.
